# -*- coding: utf-8 -*-
"""Meu bot Telegram.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vmtJ2bg5LDwiO0nf75lxyovE_IOUSRrZ
"""

pip install pytelegrambotapi

import telebot

CHAVE_API = "5213041393:AAHJurrybGzMAv82uR0LnMLt-zbW5D63FnE"

bot = telebot.TeleBot(CHAVE_API)

    ##Opção 1.1

@bot.message_handler(commands=["Enigma_free"])
def Enigma_free(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=br.com.well.enigma")

@bot.message_handler(commands=["Enigma_Pro"])
def Enigma_Pro(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=br.com.well.enigmapro")

@bot.message_handler(commands=["Soteador"])
def Soteador(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=br.com.well.sortear")
    
@bot.message_handler(commands=["Testa_porta"])
def Testa_porta(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=br.com.well.testaporta")
    
@bot.message_handler(commands=["Teste_SMTP"])
def Teste_SMTP(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=br.com.well.testesmtp")
    
@bot.message_handler(commands=["Soteador_Pro"])
def Soteador_Pro(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=br.com.well.sortearpro")
    
@bot.message_handler(commands=["Tia_Francy_Kids"])
def Tia_Francy_Kids(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=kids.francy.tia.com.br.tiafrancykids")

@bot.message_handler(commands=["IMC_Peso_Ideal"])
def IMC_Peso_Ideal(mensagem):
    bot.send_message(mensagem.chat.id, "https://play.google.com/store/apps/details?id=imc.maxwellfreire.aplicativo.br.imc")

    ## Guia do app Enigma 1.0

@bot.message_handler(commands=["Como_mandar_trava_ou_usar_enigma"])
def Como_mandar_trava_ou_usar_enigma(mensagem):
    bot.send_message(mensagem.chat.id, "https://www.youtube.com/watch?v=fx3WiHkGpB8") 

    ## Opcção 1.0
    
@bot.message_handler(commands=["op1"])
def op1(mensagem):
    texto = """
    O que você quer? (Clique em uma opção)
    /Enigma_free
    /Enigma_Pro
    /Soteador
    /Testa_porta
    /Teste_SMTP
    /Soteador_Pro
    /Tia_Francy_Kids
    /IMC_Peso_Ideal
    """
    bot.send_message(mensagem.chat.id, texto)

    ## Guia do app Enigma 1.1

@bot.message_handler(commands=["h"])
def h(mensagem):
    texto = """
    Ajudo em quer? (Clique em uma opção)
    /Como_mandar_trava_ou_usar_enigma
    """
    bot.send_message(mensagem.chat.id, texto)

@bot.message_handler(commands=["op2"])
def op2(mensagem):
    bot.send_message(mensagem.chat.id, "Nunca foi tão fácil de enviar uma reclamação, mande um e-mail para maxwellplayaplicativos@gmail.com")

@bot.message_handler(commands=["op3"])
def op3(mensagem):
    bot.send_message(mensagem.chat.id, "Seja bem vindo ao grupo Enigma para quem entrou recetemente.")

@bot.message_handler(commands=["op4"])
def op4(mensagem):
    bot.send_message(mensagem.chat.id, "Instagram http://encurtador.com.br/elPQ6\nTiktok https://www.tiktok.com/@maxwellfreire0?\nFacebook http://encurtador.com.br/npyIM\nYoutube http://encurtador.com.br/ijBR4\nSite oficial https://maxwellplay.blogspot.com/")
    
@bot.message_handler(commands=["op5"])
def op5(mensagem):
    bot.send_message(mensagem.chat.id, "https://www.mediafire.com/file/ontevckvnth2qkc/Pack_papeis_de_parede%2528Enigma%25F0%259F%25A7%2599%25F0%259F%258F%25BC%25E2%2580%258D%25E2%2599%2582%25EF%25B8%258F%2529.rar/file")

@bot.message_handler(commands=["op6"])
def op6(mensagem):
    bot.send_message(mensagem.chat.id, "Baixa o app e use os recursos. Sou apenas auxiliar do Max.")


    ## Configuração inicial

def verificar(mensagem):
    return True

@bot.message_handler(func=verificar)
def responder(mensagem):
    texto = """
    Lembrete: O bot não tem hospedagem. 🤖

    Escolha uma opção para continuar (Clique no item):
     /op1 Apps do Max
     /op2 Reclamar de um app
     /op3 Dê boas vindas no grupo Enigma
     /op4 Redes sociais do Max
     /op5 Baixar papeis de parede Enigma
     /op6 Baixar travas do Enigma
     /h Guia Enigma (yt)
     """
    bot.reply_to(mensagem, texto)

bot.polling()